# Generated by Django 5.2.17 on 2026-10-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RateCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=250, unique=True)),
                ("count", models.PositiveIntegerField(default=0)),
                ("expires", models.DateTimeField(db_index=True)),
            ],
        ),
    ]
