# Generated by Django 5.2.17 on 2026-10-07 14:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttemptThrottle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=200, unique=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("blocked_until", models.DateTimeField(blank=True, null=True)),
                (
                    "last_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SecurityConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "login_history_days",
                    models.PositiveIntegerField(
                        default=365,
                        help_text="Login records older than this are deleted automatically (0 = keep forever).",
                    ),
                ),
                (
                    "password_reuse_block",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Allow reusing old passwords"),
                            (1, "Block the current password"),
                            (5, "Block the 5 most recent passwords"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "whitelist",
                    models.TextField(
                        blank=True,
                        help_text="IP addresses or ranges (like 203.0.113.0/24) that are never blocked, one per line; anything after # is a note.",
                    ),
                ),
                (
                    "tracking_enabled",
                    models.BooleanField(
                        default=True, help_text="Record page visits for Trending."
                    ),
                ),
                (
                    "tracking_days",
                    models.PositiveIntegerField(
                        default=90,
                        help_text="Visit records older than this many days are deleted.",
                    ),
                ),
                (
                    "trending_for_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Let every staff member see Trending (by default only administrators can).",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Security settings",
                "verbose_name_plural": "Security settings",
            },
        ),
        migrations.CreateModel(
            name="SecurityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "match",
                    models.CharField(
                        choices=[
                            ("all", "All conditions (AND)"),
                            ("any", "Any condition (OR)"),
                        ],
                        default="all",
                        max_length=3,
                    ),
                ),
                ("conditions", models.JSONField(blank=True, default=list)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            (
                                "block_alert",
                                "Block the address and alert administrators",
                            ),
                            ("block", "Block the address quietly"),
                            ("alert", "Only alert administrators"),
                        ],
                        default="block_alert",
                        max_length=12,
                    ),
                ),
                ("times_matched", models.PositiveIntegerField(default=0)),
                ("last_matched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="VisitorIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("hit_count", models.PositiveIntegerField(default=0)),
                ("blocked", models.BooleanField(default=False)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("city", models.CharField(blank=True, max_length=80)),
                ("region", models.CharField(blank=True, max_length=80)),
                (
                    "country",
                    models.CharField(
                        blank=True, help_text="Two-letter country code.", max_length=2
                    ),
                ),
                (
                    "located",
                    models.BooleanField(
                        default=False,
                        help_text="Location lookup done (it may still be unknown).",
                    ),
                ),
                (
                    "recent_hits",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Times (Unix seconds) of recent visits and sign-in tries, for the rules.",
                    ),
                ),
                (
                    "rule_alerts",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{rule id: Unix time of the last alert}.",
                    ),
                ),
                ("blocked_at", models.DateTimeField(blank=True, null=True)),
                ("block_reason", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Visitor IP",
                "ordering": ["-hit_count"],
            },
        ),
        migrations.CreateModel(
            name="AccountSecurity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("must_change_password", models.BooleanField(default=False)),
                ("password_changed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoginLockout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(db_index=True, max_length=150, unique=True),
                ),
                ("failed_attempts", models.PositiveIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("last_failed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_lockouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visitor_id", models.CharField(db_index=True, max_length=32)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("path", models.CharField(db_index=True, max_length=300)),
                (
                    "referrer",
                    models.CharField(
                        blank=True,
                        help_text="Site they came from, if any.",
                        max_length=120,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True, help_text="phone, tablet or computer", max_length=10
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PasswordHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="UnlockCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_hash", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlock_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40, unique=True)),
                ("device", models.CharField(blank=True, max_length=120)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="LoginEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(help_text="What was typed.", max_length=150),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("ok", "Signed in"),
                            ("bad_password", "Wrong password"),
                            ("locked", "Blocked: account locked"),
                            ("unknown_user", "No such account"),
                            ("inactive", "Account deactivated"),
                            ("otp_unlock", "Unlocked with a code"),
                        ],
                        max_length=14,
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        blank=True,
                        help_text="member or admin login page.",
                        max_length=12,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("device", models.CharField(blank=True, max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="security_lo_user_id_b8e272_idx",
                    )
                ],
            },
        ),
    ]
