# Generated by Django 5.2.17 on 2026-10-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="system",
            field=models.BooleanField(
                default=False,
                help_text="A message from the site itself, not from another member.",
            ),
        ),
    ]
